# todos: move to config.xml
# export _JAVA_OPTIONS="-Xmx1g"
rule prep_data:
    input: 
        "/datastore/homes3/s1804374/kai_lambda/fastqgz_files.fastq.gz/{sample}.fastq.gz"
    output: 
        "data/{sample}.fastq.gz"
    shell: 
        "cp {input} {output}"

rule porechop:
    input: 
        "data/{sample}.fastq.gz"
    output: 
        "data/pc_{sample}.fastq.gz"
    shell: 
        "porechop -i {input} -o {output}"

rule fastqc:
    input:
        "data/pc_{sample}.fastq.gz"
    output:
        "report/pc_{sample}_fastqc.html",
        "report/pc_{sample}_fastqc.zip"
    shell:
        "fastqc --threads 8 --outdir report {input}"
        
rule nanofilt:
    input: 
        "data/pc_{sample}.fastq.gz"
    output:
        "data/PCNF_{sample}.fastq.gz"
    shell:
        "gunzip -c {input} | NanoFilt | gzip > {output}"
    
rule nanoplot:
    input:
        "data/PCNF_{sample}.fastq.gz"
    output:
        "report/PCNF_{sample}_NanoPlot.html"
        "report/PCNF_{sample}_NanoStats.txt"
    shell:
        "Nanoplot --threads 6 --fastq {input} --outdir report"
      


