rule_opt: "vulcan"
fastq_data: "/datastore/homes3/s1804374/kai_lambda/fastqgz_files.fastq.gz/{sample}.fastq.gz"
reference: "/datastore/homes3/s1804374/kai_lambda/J02459.fasta"
benchmarks: "/datastore/homes3/s1804374/kai_bench/benchmarks/*/{sample}.txt"