# ====================================== to be left unmodified ======================================
rule_opt: "vulcan"
work_dir_path: "./workdir"

# ====================================== to be modified by user ======================================
# sample name 
sample: "87.5_15k"

# path to input fastq file(s)
77.5_7k_badreads: "../lambda_test_data/77.5_7k_badreads.fastq.gz"
77.5_15k_badreads: "../lambda_test_data/77.5_15k_badreads.fastq.gz"
77.5_60k_badreads: "../lambda_test_data/77.5_60k_badreads.fastq.gz"

87.5_7k_badreads: "../lambda_test_data/87.5_7k_badreads.fastq.gz"
87.5_15k_badreads: "../lambda_test_data/87.5_15k_badreads.fastq.gz"
87.5_60k_badreads: "../lambda_test_data/87.5_60k_badreads.fastq.gz"

97.5_7k_badreads: "../lambda_test_data/97.5_7k_badreads.fastq.gz"
97.5_15k_badreads: "../lambda_test_data/97.5_15k_badreads.fastq.gz"
97.5_60k_badreads: "../lambda_test_data/97.5_60k_badreads.fastq.gz"

#  path to reference genome
reference: "../lambda_test_data/lambda_reference_genome.fasta"

# nanoQ minimum quality threshold 
nanoQ_mbt: 10

# threads to be used for:
porechop_threads: 12
fastQC_threads: 8
Pre_alignment_NanoPlot_threads: 8
vulcan_threads: 8
aligned_nanoplot_threads: 8



