rule_opt: "vulcan"
fastq_data: "/datastore/homes3/s1804374/kai_lambda/fastqgz_files.fastq.gz/"
test_path: "/datastore/homes3/s1804374/kai_lambda/test_fastqgz_files/"
reference: "/datastore/homes3/s1804374/kai_lambda/J02459.fasta"
mm2_bench: ["PoreChop", "NanoFilt", "FastQC", "Pre-alignment_NanoPlot", "Minimap2", "Post-alignment_NanoPlot"]
vulcan_bench: ["PoreChop", "NanoFilt", "FastQC", "Pre-alignment_NanoPlot", "Vulcan", "Post-alignment_NanoPlot"]
work_dir_path: "./workdir"
